### ISSUE TITLE
Minecraft 1.8 support

### ISSUE THREAD

**Issue by QuickScoP3s** [jajo-11/Schematic_to_Java_Python_3#1]
Can you change the generation in the java file to support minecraft 1.8?
Block generation in 1.8 changed a lot from 1.7!

**Comment by jajo-11** [comment]
The Project is on hold for now, but I might look into it on the weekend.
(I tried to rewrite some parts last time I edited the program so it might take some time)

**Comment by Zaphodious** [comment]
I just forked your package, hoping to do some of the update work (it's either this, or I'm going to be doing a _lot_ of find-replace while modding). The Qt wiki seems to be down atm, however, and installing PySide without the installer is a hassle. Could you kick over the installer for it, if you're on Windows?

**Comment by jajo-11** [comment]
just go to \Python34\Scripts open cmd and type "pip install pyside"

**Comment by Zaphodious** [comment]
Fun fact - Ninite.com installs Python 2. I feel so incredibly smart right now.
